version: '2'
services:
  web:
    container_name: "humi-nginx"
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./:/code
      - ./docker-config/configuration/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: "humi-php7-fpm"
    build:
      context: .
      dockerfile: ./docker-config/app.docker #used for php-fpm
    volumes:
      - ./:/code
